apiVersion: apps/v1
kind: Deployment
metadata:
  name: comryde-app-deployment
spec:
  selector:
    matchLabels:
      app: comryde-app
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: comryde-app
    spec:
      containers:
      - name: comryde-app
        image: ECR_REG/ECR_REPO:IMAGE_TAG
        ports:
        - containerPort: 80

