apiVersion: v1
kind: Service
metadata:
  name: comryde-app
  labels:
    app: comryde-app
    tier: app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: comryde-app
